### ISSUE TITLE
python软件包报错

### ISSUE THREAD

**Issue by zcylly** [here200/CCTalk-Video-Download-Extension#1]
能否提供request文件，usage1.py文件中的部分软件包似乎因为版本问题不能通过pip安装

**Comment by here200** [comment]
我已经上传了 requirements.txt ，里边包含了该项目使用到的依赖包版本。
在该文件的目录下，通过 命令行窗口CMD运行 python -m pip install -r requirements.txt
即可安装

![image](https://user-images.githubusercontent.com/41093691/232074486-2dbfda99-6ee1-47e8-ad65-e7c00fe5ed11.png)

**Comment by here200** [comment]
我用 pycharm的虚拟环境进行测试，发现 跟包的版本关系不大。

**Comment by JAY-ZCY** [comment]
是的，不是本地模块的问题，cctalk官网的视频链接网址已经更改，应该需要对ky_cctalk的部分参数进行调整

**Comment by here200** [comment]
没有问题，本地测试过了。

![image](https://user-images.githubusercontent.com/41093691/232182735-2d8a4f89-6c23-4f3d-95db-1711ba0849e8.png)

![image](https://user-images.githubusercontent.com/41093691/232182746-9c8c665f-e96c-46c8-ad4a-4d402415fafd.png)
